/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package interfaz;

import conexion.conector;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.event.ListSelectionEvent;
import javax.swing.event.ListSelectionListener;
import javax.swing.table.AbstractTableModel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Abrahán
 */
public class admin extends javax.swing.JFrame {
    conector _conexion=new conector();
   // DefaultTableModel tablaAux;

    /**
     * Creates new form admin
     */
    public admin() {
        initComponents();
        limpiar();
        //this.activo.disable();
       // activo.setVisible(false);
        //id.setVisible(false);
       // identificadorId.setVisible(false);
        CargarUsuarios();
       
        tablaUsuarios.getTableHeader().setReorderingAllowed(false);
        tablaReportes.getTableHeader().setReorderingAllowed(false);
          seleccionarFila();
        mostrarReportes();
        
       
      //  this.tablaUsuarios= new JTable(new MyTableModel());
    }

    void limpiar(){
        this.nombre.setText("");
        this.erp.setText("");
        this.usuario.setText("");
        this.pasw1.setText("");
        this.pasw2.setText("");
        this.ruta.setText("");
        
    }
    int fila=0;
   // String id1,nombre1,erp1,usuario1,ruta1;
    void seleccionarFila(){
      //  if(this.jTabbedPane1.isEnabledAt(0)){
        
        tablaUsuarios.getSelectionModel().addListSelectionListener(new ListSelectionListener (){
            @Override
            public void valueChanged(ListSelectionEvent arg0){
            if(tablaUsuarios.getSelectedRow()!=-1){
                fila=tablaUsuarios.getSelectedRow();
                //activo.setVisible(true);
                //id.setVisible(true);
                //identificadorId.setVisible(true);
                //id.setText((String)tablaUsuarios.getValueAt(fila, 0));
                
              //  id1=(String)tablaUsuarios.getValueAt(fila, 0);
                id.setText(""+(String) tablaUsuarios.getValueAt(fila, 0));
                 nombre.setText((String) tablaUsuarios.getValueAt(fila, 1));
                 usuario.setText((String)tablaUsuarios.getValueAt(fila, 2));
                erp.setText((String)tablaUsuarios.getValueAt(fila, 5));
                
                ruta.setText((String)tablaUsuarios.getValueAt(fila, 6));
                //nombre.setText(String.valueOf(tablaUsuarios.getValueAt(fila, 1)));
               
//                boolean valor=(boolean)tablaUsuarios.getValueAt(fila, 8);
//                if(valor){
//                    activo.setSelected(true);
//                }else{
//                    activo.setSelected(false);
//                }
                
            }
            }
            
            
            //  throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
        });
        //}
    }
  
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPopupMenu1 = new javax.swing.JPopupMenu();
        editar = new javax.swing.JMenuItem();
        borrar = new javax.swing.JMenuItem();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel2 = new javax.swing.JPanel();
        jToolBar1 = new javax.swing.JToolBar();
        guardar = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JToolBar.Separator();
        jButton2 = new javax.swing.JButton();
        jSeparator2 = new javax.swing.JToolBar.Separator();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jSeparator3 = new javax.swing.JToolBar.Separator();
        jLabel4 = new javax.swing.JLabel();
        buscar = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        nombre = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        usuario = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        pasw1 = new javax.swing.JPasswordField();
        pasw2 = new javax.swing.JPasswordField();
        jLabel6 = new javax.swing.JLabel();
        rol = new javax.swing.JComboBox<>();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        erp = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        ruta = new javax.swing.JTextField();
        activo = new javax.swing.JCheckBox();
        identificadorId = new javax.swing.JLabel();
        id = new javax.swing.JLabel();
        scrollUsuarios = new javax.swing.JScrollPane();
        tablaUsuarios = new javax.swing.JTable();
        jPanel4 = new javax.swing.JPanel();
        jToolBar2 = new javax.swing.JToolBar();
        jLabel5 = new javax.swing.JLabel();
        jTextField4 = new javax.swing.JTextField();
        jScrollPane3 = new javax.swing.JScrollPane();
        tablaReportes = new javax.swing.JTable();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenu2 = new javax.swing.JMenu();

        jPopupMenu1.setComponentPopupMenu(jPopupMenu1);

        editar.setText("Editar");
        editar.setComponentPopupMenu(jPopupMenu1);
        jPopupMenu1.add(editar);

        borrar.setText("borrar");
        borrar.setComponentPopupMenu(jPopupMenu1);
        jPopupMenu1.add(borrar);

        jPopupMenu1.getAccessibleContext().setAccessibleParent(tablaUsuarios);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jTabbedPane1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTabbedPane1MouseClicked(evt);
            }
        });
        jTabbedPane1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTabbedPane1KeyPressed(evt);
            }
        });

        jPanel2.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jPanel2KeyPressed(evt);
            }
        });

        jToolBar1.setRollover(true);

        guardar.setText("Nuevo");
        guardar.setFocusable(false);
        guardar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        guardar.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        guardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                guardarActionPerformed(evt);
            }
        });
        jToolBar1.add(guardar);
        jToolBar1.add(jSeparator1);

        jButton2.setText("Cancelar");
        jButton2.setFocusable(false);
        jButton2.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton2.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jToolBar1.add(jButton2);
        jToolBar1.add(jSeparator2);

        jButton3.setText("Editar");
        jButton3.setFocusable(false);
        jButton3.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton3.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jToolBar1.add(jButton3);

        jButton4.setText("Eliminar");
        jButton4.setFocusable(false);
        jButton4.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton4.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jToolBar1.add(jButton4);
        jToolBar1.add(jSeparator3);

        jLabel4.setText("Buscar: ");
        jToolBar1.add(jLabel4);

        buscar.setText("jTextField3");
        buscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buscarActionPerformed(evt);
            }
        });
        buscar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                buscarKeyPressed(evt);
            }
        });
        jToolBar1.add(buscar);

        jLabel1.setText("Nombre");

        nombre.setText("jTextField1");

        jLabel2.setText("Nombre de usuario");

        usuario.setText("jTextField2");

        jLabel3.setText("Contraseña");

        pasw1.setText("jPasswordField1");

        pasw2.setText("jPasswordField2");

        jLabel6.setText("Repetir contraseña");

        rol.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "rol", "admin", "usuario" }));
        rol.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rolActionPerformed(evt);
            }
        });

        jLabel7.setText("Rol");

        jLabel8.setText("Código erp");

        erp.setText("jTextField1");

        jLabel9.setText("Ruta");

        ruta.setText("jTextField2");

        activo.setText("Desactivar");

        identificadorId.setText("Id");

        id.setText("jLabel11");

        tablaUsuarios.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        scrollUsuarios.setViewportView(tablaUsuarios);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jToolBar1, javax.swing.GroupLayout.DEFAULT_SIZE, 1314, Short.MAX_VALUE)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(scrollUsuarios)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel1)
                            .addComponent(jLabel3)
                            .addComponent(jLabel6)
                            .addComponent(jLabel7)
                            .addComponent(jLabel8)
                            .addComponent(jLabel9)
                            .addComponent(identificadorId))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(id, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(nombre, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 212, Short.MAX_VALUE))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(ruta, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(erp, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(rol, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(pasw2, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(pasw1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 149, Short.MAX_VALUE)
                                    .addComponent(usuario, javax.swing.GroupLayout.Alignment.LEADING))
                                .addGap(295, 295, 295)
                                .addComponent(activo)))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jToolBar1, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(22, 22, 22)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(identificadorId)
                    .addComponent(id))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(nombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(usuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(pasw1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(pasw2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6)
                    .addComponent(activo))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rol, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel8)
                    .addComponent(erp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel9)
                    .addComponent(ruta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addComponent(scrollUsuarios, javax.swing.GroupLayout.PREFERRED_SIZE, 348, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Usuarios", jPanel2);

        jToolBar2.setRollover(true);

        jLabel5.setText("Buscar");
        jToolBar2.add(jLabel5);

        jTextField4.setText("jTextField4");
        jToolBar2.add(jTextField4);

        tablaReportes.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane3.setViewportView(tablaReportes);

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jToolBar2, javax.swing.GroupLayout.DEFAULT_SIZE, 1314, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 1302, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addComponent(jToolBar2, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 694, Short.MAX_VALUE)
                .addContainerGap())
        );

        jTabbedPane1.addTab("Reportes", jPanel4);

        jMenu1.setText("File");
        jMenuBar1.add(jMenu1);

        jMenu2.setText("Edit");
        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 1316, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

/***
 * cargara la información en la tabla
 * @param evt 
 */
    private void jTabbedPane1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTabbedPane1MouseClicked
    
    }//GEN-LAST:event_jTabbedPane1MouseClicked

    /**
     * Metodo para actualizar la información sobre los usuarios
     */
    void actualizar(){
        this._conexion.mariaDB();
        if(!this.nombre.getText().isEmpty()){
            this._conexion.update("update usuarios set nombre='"+this.nombre.getText()+"' where id="+this.id.getText()+"");
        }
        
        if(!this.pasw1.getText().isEmpty()&&!this.pasw2.getText().isEmpty()){
            this._conexion.update("update usuarios set contrasenia='"+this.pasw1.getText()+"' where id="+this.id.getText()+"");
        }else{
           JOptionPane.showMessageDialog(this, "Para actualizar la contraseña, tienen que ser iguales");
        }
        
        if(rol.getSelectedIndex()!=0){
            this._conexion.update("update usuarios set rol='"+this.rol.getSelectedItem().toString()+"' where id="+this.id.getText()+"");
        }
            
        if(!this.erp.getText().isEmpty()){
            this._conexion.update("update usuarios set codigoerp='"+this.erp.getText()+"' where id="+this.id.getText()+"");
        }
        
        if(!this.ruta.getText().isEmpty()){
             this._conexion.update("update usuarios set ruta='"+this.ruta.getText()+"' where id="+this.id.getText()+"");
        }
        
        if(this.activo.isSelected()==true){
            this._conexion.update("update usuarios set activo='0' where id="+this.id.getText()+"");
        }
        
        this._conexion.cerrarConeccion();
        
        
    }
    
    
    
    private void jTabbedPane1KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTabbedPane1KeyPressed
        // TODO add your handling code here:
        
        if(this.jTabbedPane1.isEnabledAt(0)){
        if(evt.getKeyCode()==java.awt.event.KeyEvent.VK_F5){
            
                CargarUsuarios();
            
        }
        }else if(this.jTabbedPane1.isEnabledAt(1)){
         //   buscarT("select * from usuarios");
//            
//             this._conexion.mariaDB();
//       // this.tablaAux=this._conexion.estructurarTabla(sql);
//        this.tablaUsuarios= new javax.swing.JTable(this._conexion.estructurarTabla("select * from usuarios")){
//            @Override
//            public boolean isCellEditable(int row, int column){
//                return false;
//            }
//        };
//        this.scrollUsuarios.getViewport().add(this.tablaUsuarios);
//        this._conexion.cerrarConeccion();
            
            
        }
        
        
        
    }//GEN-LAST:event_jTabbedPane1KeyPressed

    void CargarUsuarios(){
        String tabla="select * from usuarios";
                this._conexion.mariaDB();
        //this.tablaAux=this._conexion.estructurarTabla(tabla);
        this.tablaUsuarios= new javax.swing.JTable(this._conexion.estructurarTabla(tabla)){
            @Override
            public boolean isCellEditable(int row, int column){
                return false;
            }
        };
        this.scrollUsuarios.getViewport().add(this.tablaUsuarios);
        this._conexion.cerrarConeccion();
    }
    
    
    private void jPanel2KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jPanel2KeyPressed
        // TODO add your handling code here:
        if(evt.getKeyCode()==java.awt.event.KeyEvent.VK_F5){
            String sql="select * from usuarios";
            //buscarT(sql);
            
             this._conexion.mariaDB();
       // this.tablaAux=this._conexion.estructurarTabla(sql);
        this.tablaUsuarios= new javax.swing.JTable(this._conexion.estructurarTabla(sql)){
            @Override
            public boolean isCellEditable(int row, int column){
                return false;
            }
        };
        this.scrollUsuarios.getViewport().add(this.tablaUsuarios);
        this._conexion.cerrarConeccion();
            
            
        }
    }//GEN-LAST:event_jPanel2KeyPressed

    private void rolActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rolActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rolActionPerformed

    private void buscarKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_buscarKeyPressed
        // TODO add your handling code here

        if(evt.getKeyCode()==java.awt.event.KeyEvent.VK_ENTER){
            if(!this.buscar.getText().isEmpty()){
                String tabla="select * from usuarios where nombre like '%"+this.buscar.getText()+"%' or"
                + " usuario like '%"+this.buscar.getText()+"%'";
               // buscarT(tabla);
               this._conexion.mariaDB();
       // this.tablaAux=this._conexion.estructurarTabla(sql);
       this.tablaUsuarios= new javax.swing.JTable(this._conexion.estructurarTabla(tabla)){
            @Override
            public boolean isCellEditable(int row, int column){
               return false;
           }
       };
        this.scrollUsuarios.getViewport().add(this.tablaUsuarios);
        this._conexion.cerrarConeccion();
            }else{
                JOptionPane.showMessageDialog(this, "El campo de busqueda está vacío");
            }
        }
    }//GEN-LAST:event_buscarKeyPressed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        actualizar();

    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        this.limpiar();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void guardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_guardarActionPerformed
        // TODO add your handling code here:
        this._conexion.mariaDB();
        if(!this.nombre.getText().isEmpty()&&!this.usuario.getText().isEmpty()&&!this.pasw1.getText().isBlank()&&!this.pasw2.getText().isEmpty()&&!this.rol.getSelectedItem().toString().equals("rol")
            &&!this.ruta.getText().isEmpty()&&!this.erp.getText().isEmpty()){
            if(this.pasw1.getText().equals(this.pasw2.getText().toString())){
                if(!this._conexion.verificarDato("select * from usuarios where usuario='"+this.usuario.getText()+"'")){
                    this._conexion.update("insert into usuarios (nombre, usuario, contrasenia, rol, codigoerp, ruta, activo) values('"+this.nombre.getText()+"',"
                        + "'"+this.usuario.getText()+"',"
                        + "'"+this.pasw1.getText()+"',"
                        + "'"+this.rol.getSelectedItem().toString()+"',"
                        + "'"+this.erp.getText()+"',"
                        + "'"+this.ruta.getText()+"',1)");
                    limpiar();

                }else{
                    JOptionPane.showMessageDialog(rootPane,"Ya existe un usuario con esta descripción:\n"+this.usuario.getText());
                }
            }else{
                JOptionPane.showMessageDialog(rootPane,"Las contraseñas para el nuevo usuario deben de ser iguales");
            }

        }else{
            JOptionPane.showMessageDialog(rootPane,"Para dar de alta un usuario se requieren todos los datos");
        }
        this._conexion.cerrarConeccion();
    }//GEN-LAST:event_guardarActionPerformed

    private void buscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buscarActionPerformed
        // TODO add your handling code here:
        
        
        
        
        
        
    }//GEN-LAST:event_buscarActionPerformed
//
//    void buscarT(String sql){
//        
//        //String tabla="select nombre, usuario, contrasenia, rol, codigoerp, ruta from usuarios";
//        this._conexion.mariaDB();
//       // this.tablaAux=this._conexion.estructurarTabla(sql);
//        this.tablaUsuarios= new javax.swing.JTable(this._conexion.estructurarTabla(sql)){
//            @Override
//            public boolean isCellEditable(int row, int column){
//                return false;
//            }
//        };
//        this.scrollUsuarios.getViewport().add(this.tablaUsuarios);
//        this._conexion.cerrarConeccion();
//    }
//    
//    
    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(admin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(admin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(admin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(admin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new admin().setVisible(true);
            }
        });
    }
    
    
    void mostrarReportes(){
        this._conexion.mariaDB();
        String sql="select * from reportes";
       // this.tablaAux=this._conexion.estructurarTabla(sql);
        this.tablaReportes.setModel(this._conexion.estructurarTabla(sql));
        this.jScrollPane3.getViewport().add(this.tablaReportes);
        this._conexion.cerrarConeccion();
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JCheckBox activo;
    private javax.swing.JMenuItem borrar;
    private javax.swing.JTextField buscar;
    private javax.swing.JMenuItem editar;
    private javax.swing.JTextField erp;
    private javax.swing.JButton guardar;
    private javax.swing.JLabel id;
    private javax.swing.JLabel identificadorId;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPopupMenu jPopupMenu1;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JToolBar.Separator jSeparator1;
    private javax.swing.JToolBar.Separator jSeparator2;
    private javax.swing.JToolBar.Separator jSeparator3;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JToolBar jToolBar1;
    private javax.swing.JToolBar jToolBar2;
    private javax.swing.JTextField nombre;
    private javax.swing.JPasswordField pasw1;
    private javax.swing.JPasswordField pasw2;
    private javax.swing.JComboBox<String> rol;
    private javax.swing.JTextField ruta;
    private javax.swing.JScrollPane scrollUsuarios;
    private javax.swing.JTable tablaReportes;
    private javax.swing.JTable tablaUsuarios;
    private javax.swing.JTextField usuario;
    // End of variables declaration//GEN-END:variables

   
}
