/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package interfaz;

import conexion.conector;
import conexion.direccion;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author Abrahán
 */
public class loging extends javax.swing.JFrame {
conector _conector= new conector();
admin _admin = new admin();
usuario _usuario;
    /**
     * Creates new form loging
     */
    public loging() {
        initComponents();
        this.usuario.setText("");
        this.contrasenia.setText("");
    }
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        contrasenia = new javax.swing.JPasswordField();
        usuario = new javax.swing.JTextField();
        inicio = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Inicio");
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        contrasenia.setText("jPasswordField1");
        contrasenia.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                contraseniaKeyPressed(evt);
            }
        });
        getContentPane().add(contrasenia, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 430, 170, -1));

        usuario.setText("jTextField1");
        usuario.setActionCommand("<Not Set>");
        usuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                usuarioActionPerformed(evt);
            }
        });
        getContentPane().add(usuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 390, 170, -1));

        inicio.setText("Inicio");
        inicio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inicioActionPerformed(evt);
            }
        });
        getContentPane().add(inicio, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 460, -1, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/LOGO2chiquito.png"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(-50, -70, 670, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void usuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_usuarioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_usuarioActionPerformed
direccion _direccion= new direccion();
    void loging() throws IOException{
        this._conector.mariaDB();
        if(!this.usuario.getText().isEmpty()&&!this.contrasenia.getText().isEmpty()){
            String respuesta=_conector.devolverDato("select rol from usuarios where usuario='"+usuario.getText()+"' and contrasenia='"+contrasenia.getText()+"'","rol");
            System.out.println(""+respuesta);
            if(respuesta.equals("admin")){
                _conector.cerrarConeccion();
                 _direccion.guardarUsuario(this.usuario.getText());
                 _admin= new admin();
                _admin.setVisible(true);
                dispose();
            }else if(respuesta.equals("usuario")){
                 _conector.cerrarConeccion();
                _direccion.guardarUsuario(this.usuario.getText());
                _usuario= new usuario();
                _usuario.setVisible(true);
                
               // xusuario.setVisible(true);
                dispose();
            }else{
               JOptionPane.showMessageDialog(rootPane, "Ocurrio un problema en la conexión"); 
            }
        }else{
            JOptionPane.showMessageDialog(rootPane, "Los datos no pueden estar vacios");
        }
        this._conector.cerrarConeccion(); 
    }
    
    //012 470 027185320280
    private void inicioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inicioActionPerformed
    try {
        // TODO add your handling code here:
        loging();
    } catch (IOException ex) {
        Logger.getLogger(loging.class.getName()).log(Level.SEVERE, null, ex);
    }
        
    }//GEN-LAST:event_inicioActionPerformed

    private void contraseniaKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_contraseniaKeyPressed
        // TODO add your handling code here:
        if(evt.getKeyCode()==java.awt.event.KeyEvent.VK_ENTER){
            try { 
                loging();
            } catch (IOException ex) {
                Logger.getLogger(loging.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
      
        
    }//GEN-LAST:event_contraseniaKeyPressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(loging.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(loging.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(loging.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(loging.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new loging().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPasswordField contrasenia;
    private javax.swing.JButton inicio;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JTextField usuario;
    // End of variables declaration//GEN-END:variables
}
